Feat/ec 4943 restrict to supported media
europeana/oembed.js pull request #9
Opened 2020-12-08 15:29 UTC by LeoniePeters

2020-12-09 09:22 UTC, lbiedinger commented on src/response.js
> +const embeddableRights = (rights) => {
Rename to `embeddingPermitted`

2020-12-09 09:22 UTC, lbiedinger commented on src/response.js
> +const embeddableMediaType = (mediaType) => {
Rename to `mediaTypeEmbeddable`

2020-12-14 09:08 UTC, pixelomo commented on src/response.js
> +    .filter(media => media !== undefined);
It might be better to use `typeof media !== 'undefined'`

2020-12-14 09:22 UTC, rwd commented on src/response.js
> +    .filter(media => media !== undefined);
Not necessary as this is a Node.js app.

2020-12-14 13:24 UTC, rwd requested changes

2020-12-14 13:24 UTC, rwd commented on src/response.js
> +        ['audio', 'image', 'video'].includes(mediaType.split('/')[0]);
There is one additional case we need to support, where the full media type is `application/dash+xml`.

Please also include in a comment a link to the source logic for this: https://github.com/europeana/metis-framework/blob/v2.1/metis-common/src/main/java/eu/europeana/metis/utils/MediaType.java#L41-L64

2020-12-15 09:26 UTC, rwd approved these changes

2020-12-15 09:26 UTC, merged